export { default as router } from './reducers/router.reducer'
export { default as currentModal } from './reducers/currentModal.reducer'
export { default as fetchContactsState } from './reducers/fetchContactsState.reducer'
export { default as contacts } from './reducers/contacts.reducer'
export { default as search } from './reducers/search.reducer'
export { default as evenOnly } from './reducers/evenOnly.reducer'
export { default as total } from './reducers/total.reducer'
export { default as page } from './reducers/page.reducer'
